spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/test_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    tidb:
      url: jdbc:mysql://localhost:4000/test_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

hydra:
  heterogeneous-compare:
    auto-compare-on-startup: true
    verbose-output: true
    compare-configs:
      - name: "mysql-to-tidb-compare"
        source-table:
          type: "mysql"
          data-source-name: "mysqlDataSource"
          table-name: "user_info"
        target-table:
          type: "tidb"
          data-source-name: "tidbDataSource"
          table-name: "user_info"
        ignore-fields:
          - "create_time"
          - "update_time"
        ignore-types:
          - "COMMENT"
          - "INDEX" 